### ISSUE TITLE
studiounit.gif link broken in prometheus metrics

### ISSUE THREAD

**Issue by sbarber2** [spotfiresoftware/tibco-streaming-samples#59]
On the https://github.com/TIBCOSoftware/tibco-streaming-samples/blob/10.6.1/web/prometheus-metrics/prometheus-metrics-war/src/site/markdown/index.md page, the https://github.com/TIBCOSoftware/tibco-streaming-samples/blob/10.6.1/nativelibrary/nar/nar-eventflow/src/site/resources/images/studiounit.gif link gives a 404.

**Comment by TIBCOjstinton** [comment]
Thanks, should be fixed in 10.6.1/2/3 now. Sample has been re-written in 11.0 so image was not present.
